In [60]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

In [61]:
train=pd.read_csv('train.csv')
df1=pd.read_csv('train.csv')

In [62]:
pciats = [col for col in train.columns if 'PCIAT' in col]
pciats.remove('PCIAT-Season')
pciats.remove('PCIAT-PCIAT_Total')

In [63]:
# Create 20 new variables that indicate whether or not PCIAT-PCIAT_01 through PCIAT-PCIAT_20 were NaN

for pciat in pciats:
    train[pciat + '_isnotna'] = train[pciat].notna().astype(int)

In [64]:
pciatsnotna = [col for col in train.columns if 'isnotna' in col]

#Create new variable that represents the sum o the questions answered.

train['pciatsnotna_sum'] = train[pciatsnotna].sum(axis=1)


In [65]:
train['pciatsnotna_sum'].value_counts()

pciatsnotna_sum
20    2136
0      984
19      38
18       7
15       1
17       1
10       1
Name: count, dtype: int64

In [66]:
#This removes the rows where none of the PCIAT questions were answered.train

train = train[train['pciatsnotna_sum'] != 0]

In [67]:
train['pciatsnotna_sum'].value_counts()

pciatsnotna_sum
20    2136
19      38
18       7
15       1
17       1
10       1
Name: count, dtype: int64

In [47]:
from sklearn.impute import KNNImputer

In [48]:
# define imputer
imputer = KNNImputer(n_neighbors=5, weights='uniform', metric='nan_euclidean')

In [68]:
imputations=imputer.fit_transform(train[pciats])

In [69]:
print(imputations)

[[2. 2. 1. ... 1. 0. 1.]
 [2. 2. 1. ... 1. 0. 0.]
 [0. 4. 3. ... 1. 1. 3.]
 ...
 [2. 1. 2. ... 1. 0. 1.]
 [4. 0. 3. ... 2. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [70]:
df2 = pd.DataFrame(imputations, columns=pciats)

In [71]:
df2

PCIAT-PCIAT_01  PCIAT-PCIAT_02  PCIAT-PCIAT_03  PCIAT-PCIAT_04  \
0                2.0             2.0             1.0             0.0   
1                2.0             2.0             1.0             0.0   
2                0.0             4.0             3.0             1.0   
3                5.0             5.0             5.0             2.0   
4                4.0             4.0             2.0             1.0   
...              ...             ...             ...             ...   
2179             0.0             0.0             0.0             0.0   
2180             4.0             2.0             4.0             0.0   
2181             2.0             1.0             2.0             0.0   
2182             4.0             0.0             3.0             0.0   
2183             0.0             0.0             0.0             0.0   

      PCIAT-PCIAT_05  PCIAT-PCIAT_06  PCIAT-PCIAT_07  PCIAT-PCIAT_08  \
0                1.0             0.0             0.0             0.0   
1                4.0             0.0             0.0             1.0   
2                4.0             0.0             4.0             0.0   
3                5.0             1.0             5.0             4.0   
4                3.0             0.0             0.0             1.0   
...              ...             ...             ...             ...   
2179             0.0             0.0             0.0             0.0   
2180             0.0             0.0             0.0             0.0   
2181             1.0             2.0             0.0             1.0   
2182             3.0             0.0             0.0             0.0   
2183             0.0             0.0             0.0             0.0   

      PCIAT-PCIAT_09  PCIAT-PCIAT_10  PCIAT-PCIAT_11  PCIAT-PCIAT_12  \
0                1.0             2.0             2.0             0.0   
1                0.0             1.0             1.0             0.0   
2                3.0             0.0             2.0             2.0   
3                5.0             4.0             4.0             1.0   
4                1.0             2.0             2.0             0.0   
...              ...             ...             ...             ...   
2179             0.0             0.0             0.0             0.0   
2180             0.0             2.0             0.0             0.0   
2181             2.0             1.0             2.0             0.0   
2182             0.0             0.0             2.0             0.0   
2183             0.0             0.0             0.0             0.0   

      PCIAT-PCIAT_13  PCIAT-PCIAT_14  PCIAT-PCIAT_15  PCIAT-PCIAT_16  \
0                1.0             0.0             0.0             1.0   
1                0.0             0.0             0.0             1.0   
2                4.0             3.0             4.0             4.0   
3                4.0             4.0             5.0             5.0   
4                2.0             1.0             2.0             2.0   
...              ...             ...             ...             ...   
2179             0.0             0.0             0.0             0.0   
2180             0.0             0.0             0.0             2.0   
2181             2.0             2.0             1.0             1.0   
2182             1.4             0.0             2.0             2.0   
2183             0.0             0.0             0.0             0.0   

      PCIAT-PCIAT_17  PCIAT-PCIAT_18  PCIAT-PCIAT_19  PCIAT-PCIAT_20  
0                1.0             1.0             0.0             1.0  
1                0.0             1.0             0.0             0.0  
2                1.0             1.0             1.0             3.0  
3                3.0             4.0             2.0             5.0  
4                2.0             2.0             2.0             0.0  
...              ...             ...             ...             ...  
2179             0.0             0.0             

In [72]:
train[pciats]=df2[pciats]

In [55]:
train.head()

id Basic_Demos-Enroll_Season  Basic_Demos-Age  Basic_Demos-Sex  \
0  1b5fb26f                    Spring                8                1   
1  f98bde44                    Summer               14                0   
2  b120a337                    Spring                9                1   
3  9d60665f                    Summer               13                1   
4  50a90725                      Fall               22                1   

  CGAS-Season  CGAS-CGAS_Score Physical-Season  Physical-BMI  Physical-Height  \
0      Spring             50.0          Winter     20.434833             53.5   
1         NaN              NaN             NaN           NaN              NaN   
2         NaN              NaN          Summer     14.609671             54.0   
3         NaN              NaN             NaN           NaN              NaN   
4         NaN              NaN          Winter     34.509396             65.0   

   Physical-Weight  ...  PCIAT-PCIAT_18  PCIAT-PCIAT_19  PCIAT-PCIAT_20  \
0             83.2  ...             1.0             0.0             1.0   
1              NaN  ...             1.0             0.0             0.0   
2             60.6  ...             1.0             1.0             3.0   
3              NaN  ...             4.0             2.0             5.0   
4            207.4  ...             2.0             2.0             0.0   

   PCIAT-PCIAT_Total SDS-Season  SDS-SDS_Total_Raw  SDS-SDS_Total_T  \
0               16.0     Spring               44.0             62.0   
1                NaN        NaN                NaN              NaN   
2               14.0     Spring               48.0             67.0   
3                NaN        NaN                NaN              NaN   
4               44.0     Winter               50.0             69.0   

   PreInt_EduHx-Season PreInt_EduHx-computerinternet_hoursday  sii  
0               Spring                                    1.0  0.0  
1               Summer                                    2.0  NaN  
2               Spring                                    0.0  0.0  
3               Summer                                    2.0  NaN  
4                 Fall                                    2.0  1.0  

[5 rows x 82 columns]

In [73]:
pciats

['PCIAT-PCIAT_01',
 'PCIAT-PCIAT_02',
 'PCIAT-PCIAT_03',
 'PCIAT-PCIAT_04',
 'PCIAT-PCIAT_05',
 'PCIAT-PCIAT_06',
 'PCIAT-PCIAT_07',
 'PCIAT-PCIAT_08',
 'PCIAT-PCIAT_09',
 'PCIAT-PCIAT_10',
 'PCIAT-PCIAT_11',
 'PCIAT-PCIAT_12',
 'PCIAT-PCIAT_13',
 'PCIAT-PCIAT_14',
 'PCIAT-PCIAT_15',
 'PCIAT-PCIAT_16',
 'PCIAT-PCIAT_17',
 'PCIAT-PCIAT_18',
 'PCIAT-PCIAT_19',
 'PCIAT-PCIAT_20']

In [74]:
train['PCIAT_Total_Imputed'] = train[pciats].sum(axis=1)

In [78]:
(train[pciats]-df1[pciats]).describe()

PCIAT-PCIAT_01  PCIAT-PCIAT_02  PCIAT-PCIAT_03  PCIAT-PCIAT_04  \
count     1531.000000     1531.000000     1530.000000     1530.000000   
mean         0.013847       -0.008361        0.041961       -0.026928   
std          2.401365        2.384883        2.250172        1.672212   
min         -5.000000       -5.000000       -5.000000       -5.000000   
25%         -2.000000       -2.000000       -2.000000       -1.000000   
50%          0.000000        0.000000        0.000000        0.000000   
75%          2.000000        2.000000        2.000000        1.000000   
max          5.000000        5.000000        5.000000        5.000000   

       PCIAT-PCIAT_05  PCIAT-PCIAT_06  PCIAT-PCIAT_07  PCIAT-PCIAT_08  \
count     1529.000000     1530.000000     1528.000000     1529.000000   
mean         0.003663        0.022876       -0.023298        0.014258   
std          2.462544        1.756647        1.470917        1.864755   
min         -5.000000       -5.000000       -5.000000       -5.000000   
25%         -2.000000       -1.000000       -1.000000       -1.000000   
50%          0.000000        0.000000        0.000000        0.000000   
75%          2.000000        1.000000        0.000000        1.000000   
max          5.000000        5.000000        5.000000        5.000000   

       PCIAT-PCIAT_09  PCIAT-PCIAT_10  PCIAT-PCIAT_11  PCIAT-PCIAT_12  \
count     1528.000000     1531.000000     1531.000000     1528.000000   
mean        -0.011126       -0.000131        0.009144       -0.007592   
std          1.713097        1.845971        2.227850        0.686702   
min         -5.000000       -5.000000       -5.000000       -4.000000   
25%         -1.000000       -1.000000       -2.000000        0.000000   
50%          0.000000        0.000000        0.000000        0.000000   
75%          1.000000        1.000000        2.000000        0.000000   
max          5.000000        5.000000        5.000000        5.000000   

       PCIAT-PCIAT_13  PCIAT-PCIAT_14  PCIAT-PCIAT_15  PCIAT-PCIAT_16  \
count     1527.000000     1529.000000     1529.000000     1527.000000   
mean         0.016241       -0.031001        0.022368       -0.009561   
std          2.022909        1.863905        2.082562        2.145748   
min         -5.000000       -5.000000       -5.000000       -5.000000   
25%         -1.000000       -1.000000       -1.000000       -1.000000   
50%          0.000000        0.000000        0.000000        0.000000   
75%          1.000000        1.000000        1.000000        1.000000   
max          5.000000        5.000000        5.000000        5.000000   

       PCIAT-PCIAT_17  PCIAT-PCIAT_18  PCIAT-PCIAT_19  PCIAT-PCIAT_20  
count     1526.000000     1526.000000     1528.000000     1531.000000  
mean         0.018611        0.004718        0.006283        0.006140  
std          1.999690        2.188609        1.903077        1.664136  
min         -5.000000       -5.000000       -5.000000       -5.000000  
25%         -1.000000       -1.000000       -1.000000       -1.000000  
50%          0.000000        0.000000        0.000000        0.000000  
75%          1.000000        1.000000        1.000000        1.000000  
max          5.000000        5.000000        5.000000        5.000000